apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-mysql-pvc
spec:
  storageClassName: ""
  volumeName: drupal-mysql-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi