apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysql
  name: mysql
spec:
  ports:
  - name: 3306-30007
    port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 30007
  selector:
    app: mysql-deployment
  type: NodePort
status:
  loadBalancer: {}